In [1]:
import cv2

# read image

In [38]:
# colord image
img = cv2.imread('image2.jpg',1)

In [4]:
img

array([[[ 28,  22,  17],
        [ 29,  23,  18],
        [ 29,  23,  18],
        ...,
        [221, 232, 236],
        [223, 234, 238],
        [224, 235, 239]],

       [[ 28,  22,  17],
        [ 29,  23,  18],
        [ 29,  23,  18],
        ...,
        [221, 232, 236],
        [223, 234, 238],
        [223, 234, 238]],

       [[ 28,  22,  17],
        [ 28,  22,  17],
        [ 29,  23,  18],
        ...,
        [222, 233, 237],
        [222, 233, 237],
        [223, 234, 238]],

       ...,

       [[188, 145,  96],
        [189, 146,  97],
        [190, 147,  98],
        ...,
        [ 68,  45,   0],
        [ 72,  49,   4],
        [ 76,  53,   8]],

       [[189, 146,  97],
        [190, 147,  98],
        [191, 148,  99],
        ...,
        [ 68,  45,   0],
        [ 71,  49,   7],
        [ 76,  54,  12]],

       [[188, 145,  96],
        [188, 145,  96],
        [189, 146,  97],
        ...,
        [ 68,  45,   0],
        [ 71,  49,   7],
        [ 77,  55,  13]]

In [39]:
# black & white 
img_bw = cv2.imread('image2.jpg',0)

In [40]:
img_bw

array([[245, 245, 245, ..., 221, 221, 221],
       [245, 245, 245, ..., 221, 221, 221],
       [245, 245, 245, ..., 221, 221, 221],
       ...,
       [195, 195, 196, ..., 179, 180, 173],
       [196, 196, 197, ..., 176, 181, 177],
       [197, 197, 198, ..., 173, 182, 183]], dtype=uint8)

In [6]:
print(type(img))

<class 'numpy.ndarray'>


In [41]:
img.shape

(800, 1200, 3)

In [42]:
img_bw.shape

(800, 1200)

# display image

In [43]:
cv2.imshow('Faces', img_bw)
cv2.waitKey(0)
# cv2.waitKey(2000)
cv2.destroyAllWindows()

# resize image

In [44]:
rs_img = cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2)))

In [45]:
cv2.imshow('Resize', rs_img)
#cv2.waitKey(0)
cv2.waitKey(2000)
cv2.destroyAllWindows()

# face detection 

In [46]:
# creating cascade classifier object
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")

In [47]:
# reading the image
img2 = cv2.imread("image2.jpg")

In [48]:
# reading the image as gray scale image
gray_img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

In [49]:
# search the co-ordinate of the image
faces = face_cascade.detectMultiScale(gray_img2, scaleFactor=1.05, minNeighbors=5)

In [34]:
print(type(faces))

<class 'numpy.ndarray'>


In [50]:
print(faces)

[[ 828  435  152  152]
 [ 227   35  136  136]
 [ 431   37  134  134]
 [1036   30  140  140]
 [ 636   40  129  129]
 [  25  236  138  138]
 [ 828   29  153  153]
 [ 634  240  133  133]
 [  28   41  129  129]
 [ 224  235  142  142]
 [ 420  439  144  144]
 [1035  238  140  140]
 [ 418  229  161  161]
 [ 835  240  139  139]
 [  30  441  135  135]
 [ 219  432  153  153]
 [1038  443  134  134]
 [ 626  436  148  148]
 [ 434  646  131  131]
 [  31  646  128  128]
 [ 837  642  134  134]
 [ 631  639  140  140]
 [1035  642  139  139]
 [ 227  643  136  136]]


In [51]:
# plotting rectangle
for x,y,w,h in faces:
    img = cv2.rectangle(img2, (x,y), (x+w,y+h), (0,255,0), 3)

In [52]:
#resize = cv2.resize(img, (int(img.shape)))
cv2.imshow('Gray', img)
cv2.waitKey(0)
# cv2.waitKey(2000)
cv2.destroyAllWindows()